CREATE TABLE STUDENT_T (
    STUDENT_NO      NUMBER NOT NULL PRIMARY KEY,
    STUDENT_NAME    VARCHAR2(20 BYTE) NOT NULL,
    STUDENT_GRADE   NUMBER NOT NULL,
    STUDENT_TEL     VARCHAR2(40 BYTE) NOT NULL
);

CREATE TABLE SUBJECT_T (
    SUBJECT_NO      NUMBER NOT NULL PRIMARY KEY,
    SUBJECT_NAME    VARCHAR2(40 BYTE) NOT NULL
);

CREATE TABLE ENROLMENT_T (
    STUDENT_NO NUMBER REFERENCES STUDENT_T(STUDENT_NO),
    SUBJECT_NO NUMBER REFERENCES SUBJECT_T(SUBJECT_NO)
);