--DDL
DROP TABLE CUSTOMER_T;
DROP TABLE BANK_T;

CREATE TABLE BANK_T (
    BANK_CODE VARCHAR2(20 BYTE) NOT NULL,
    BANK_NAME VARCHAR2(30 BYTE),
    
    -- 제약 조건 임의 이름 지정
    CONSTRAINT PK_BANK PRIMARY KEY(BANK_CODE)
);

CREATE TABLE CUSTOMER_T (
    CUST_NO NUMBER NOT NULL,
    CUST_NAME VARCHAR2(30 BYTE) NOT NULL,
    CUST_PHONE VARCHAR2(30 BYTE) UNIQUE,
    CUST_AGE NUMBER(3) CHECK(CUST_AGE >= 0 AND CUST_AGE <= 120), -- CHECK(CUST_AGE BETWEEN 0 AND 120) 동일한 방법
    BANK_CODE VARCHAR2(20 BYTE),
    
    CONSTRAINT PK_CUSTOMER PRIMARY KEY(CUST_NO),
    CONSTRAINT FK_CUSTOMER_BANK FOREIGN KEY(BANK_CODE) REFERENCES BANK_T(BANK_CODE)
);

SELECT * FROM USER_CONSTRAINTS;

/*
칼럼 추가 : ALTER TABLE [TABLE_NAME] ADD [COLUMN_NAME] [DATA_TYPE] [CONDITION]
칼럼 수정 : ALTER TABLE [TABLE_NAME] MODIFY [COLUMN_NAME] [DATA_TYPE] [CONDITION]
칼럼 삭제 : ALTER TABLE [TABLE_NAME] DROP COLUMN [COLUMN_NAME]
칼럼 이름 변경 : ALTER TABLE [TABLE_NAME] RENAME COLUMN [ORIGIN_NAME] TO [NEW_NAME]
테이블명 변경 : ALTER TABLE [TABLE_NAME] RENAME TO [NEW_NAME]
*/

ALTER TABLE BANK_T ADD BANK_TEL VARCHAR2(20 BYTE) NOT NULL;
ALTER TABLE BANK_T MODIFY BANK_NAME VARCHAR2(15 BYTE) UNIQUE;
ALTER TABLE CUSTOMER_T DROP COLUMN CUST_AGE;
ALTER TABLE CUSTOMER_T RENAME COLUMN CUST_PHONE TO CUST_TEL;

ALTER TABLE CUSTOMER_T ADD CUST_GRADE VARCHAR2(6 BYTE) CHECK(CUST_GRADE IN ('VIP', 'GOLD', 'SILVER', 'BRONZE'));
--CHECK(CUST_GRADE = 'VIP' OR);
--ALTER TABLE CUSTOMER_T ADD CONSTRAINT CHECK_GRADE CHECK(CUST_GRADE IN ('VIP', 'GOLD', 'SILVER', 'BRONZE'));

--ALTER TABLE CUSTOMER_T drop constraint SYS_C007395;   --이건 아예 제약조건 삭제 ㅋㅋ
ALTER TABLE CUSTOMER_T MODIFY CUST_NAME VARCHAR2(30 BYTE) NULL; -- 이미 NOT NULL인 상태에서 NULL을 안쓰면 수정 자체가 안됨
ALTER TABLE CUSTOMER_T RENAME TO CUST_T;

/*
기본키 수정
ALTER TABLE 테이블명 ADD CONSTRAINT 제약조건명 PRIMARY KEY 칼럼명
삭제
    1 ALTER TABLE 테이블명 DROP CONSTRAINT 제약조건명
    2 ALTER TABLE 테이블명 DROP PRIMARY KEY
    
FK
추가
    ALTER TABLE 자식TB ADD CONSTRAINT CONDITION FOREIGN KEY(COLUMN_NAME) REFERENCES 부모TB(참조COLUMN) [OPTION - ON DELETE CASCADE]
삭제
    ALTER TABLE TBNAME DROP CONSTRAINT CONDITION_NAME
비활성
    ALTER TABLE TBNAME DISABLE CONSTRAINT CONDITION_NAME
활성
    ALTER TABLE TBNAME ENABLE CONSTRAINT CONDITION_NAME
*/

/*ALTER TABLE CUST_T DISABLE CONSTRAINT FK_CUSTOMER_BANK;
ALTER TABLE CUST_T ENABLE CONSTRAINT FK_CUSTOMER_BANK;*/