/*
Data Query Language
SELECT *
FROM TABLE_NAME
WHERE CONDITION
GROUP BY COLMN1, COLNM2,.....
HAVING CONDITION
ORDER BY COLUMN ASC|DESC,.....
*/

SELECT * FROM DEPARTMENT_TB ORDER BY DEPT_NAME;
SELECT DEPARTMENT_TB.DEPT_NO, DEPARTMENT_TB.DEPT_NAME, DEPARTMENT_TB.LOCATION FROM DEPARTMENT_TB;
SELECT D.DEPT_NO, D.DEPT_NAME, D.LOCATION FROM DEPARTMENT_TB D; -- 별명을 이렇게 하네 오라클은

SELECT  DEPT_NO AS 부서번호, 
        DEPT_NAME AS 부서명, 
        LOCATION AS 위치
    FROM DEPARTMENT_TB;
    
SELECT DISTINCT LOCATION FROM DEPARTMENT_TB;    -- 중복 제거

SELECT LOCATION FROM DEPARTMENT_TB GROUP BY LOCATION;

SELECT COUNT(LOCATION) AS L_COUNT FROM DEPARTMENT_TB GROUP BY LOCATION;

/*
주요 조건식 작성 방법
1. 칼럼 = 값
2. 칼럼 BETWEEN 값1 AND 값2
3. 칼럼 IN(값1, 값2)
4. 칼럼 IS NULL
5. 칼럼 IS NOT NULL
6. 칼럼 LIKE 값
*/

SELECT * FROM DEPARTMENT_TB WHERE DEPT_NO = 21;
SELECT * FROM DEPARTMENT_TB WHERE LOCATION = '서울';

SELECT * FROM EMPLOYEE_TB WHERE SALARY >= 3000000;
SELECT * FROM EMPLOYEE_TB WHERE SALARY BETWEEN 2000000 AND 3000000;
SELECT * FROM EMPLOYEE_TB WHERE POSITION = '사원' OR POSITION = '과장';
SELECT * FROM EMPLOYEE_TB WHERE POSITION IN('사원', '과장');

/*
% 굴자수에 상관 없는 만능문자
_ 1글자를 의미하는 만능문자
*/

SELECT * FROM EMPLOYEE_TB WHERE NAME LIKE '한%';
SELECT * FROM EMPLOYEE_TB WHERE HIRE_DATE LIKE '%/09/%';