/* 날짜/시간 연산
1일을 숫자 1로 처리
1/24 1시간
1/24/60 1분
1/24/60/60 1초
*/
SELECT  TO_CHAR(SYSDATE, 'YY/MM/DD HH24:MI:SS'),
        TO_CHAR(SYSDATE + 1, 'YY/MM/DD HH24:MI:SS'),
        TO_CHAR(SYSDATE - 1, 'YY/MM/DD HH24:MI:SS'),
        TO_CHAR(SYSDATE + 1/24, 'YY/MM/DD HH24:MI:SS'),
        TO_CHAR(SYSDATE + 1/24/60, 'YY/MM/DD HH24:MI:SS'),
        TO_CHAR(SYSDATE + 1/24/60/60, 'YY/MM/DD HH24:MI:SS')
FROM DUAL;        

SELECT EMP_NO, NAME,
        SYSDATE - TO_DATE(HIRE_DATE) AS 근무일수
FROM EMPLOYEE_TB;

/* TIMESTAMP
INTERVAL 키워드 사용
YEAR, MONTH, DAY, HOUR, MINUTE, SECOND
*/
SELECT SYSTIMESTAMP + INTERVAL '1' YEAR
FROM DUAL;

-- EXTRACT(단위 FROM 날짜/시간)
SELECT  EXTRACT(YEAR FROM SYSDATE),
        EXTRACT(MONTH FROM SYSDATE),
        EXTRACT(DAY FROM SYSDATE),
        --EXTRACT(HOUR FROM SYSDATE) 오류남
        EXTRACT(HOUR FROM SYSTIMESTAMP) AS "UTC",
        EXTRACT(HOUR FROM SYSTIMESTAMP) + 9 AS "ASIA/SEOUL",
        EXTRACT(MINUTE FROM SYSTIMESTAMP),
        EXTRACT(SECOND FROM SYSTIMESTAMP)
FROM DUAL;

-- ADD_MONTHS(DATE, N)
SELECT ADD_MONTHS(SYSDATE, 1) FROM DUAL;

-- MONTHS_BETWEEN(최근, 이전)
select
    months_between(sysdate, to_date('23/1/1')) as "결과"
from dual;