/*INSERT ALL
    INTO EMPLOYEE_TB VALUES (EMPLOYEE_SEQ.NEXTVAL, 'A', 21, 'B', 'M', '23/10/01', 1)
SELECT * FROM DUAL;*/

/*
DUAL 테이블

*/

/*
TO_NUMBER(CHAR)
*/

SELECT TO_NUMBER('100') FROM DUAL;
--SELECT 시퀀스.NEXTVAL FROM DUAL;
SELECT SYSDATE FROM DUAL;
SELECT CURRENT_DATE FROM DUAL;

-- 원래 실행 안되는데 오라클 내부적으로 아래로 치환하여 처리
SELECT * FROM DEPARTMENT_TB WHERE DEPT_NO = '1';
SELECT * FROM DEPARTMENT_TB WHERE DEPT_NO = TO_NUMBER('1');

-- TO_CHAR(INT, 형식)
SELECT    TO_CHAR(SALARY)
        , TO_CHAR(SALARY, '99999999999') 
        , TO_CHAR(SALARY, '00000000000')
        , TO_CHAR(SALARY, '9,999,999')
        , TO_CHAR(SALARY, '9,999') -- 천단위 구분 기호 사용, 원본이 짧아서 오류
FROM EMPLOYEE_TB;

-- TO_DATE(문자, [형식])
-- YY, YYYY, MM, DD, AM(오전/오후), HH, HH24, MI(분2자리), SS, FF3(밀리초3자리)
SELECT  TO_DATE(HIRE_DATE),
        TO_DATE(HIRE_DATE, 'YY/MM/DD'),
        TO_DATE(HIRE_DATE, 'YY/DD/MM')
        --TO_DATE(HIRE_DATE, '11,DD,MM') 오류
        --TO_DATE(HIRE_DATE, 'HH') 오류 시간 데이터 없음
FROM EMPLOYEE_TB;

-- SYSDATE
SELECT  SYSDATE,
        TO_CHAR(SYSDATE, 'YYYY-MM-DD AM HH:MI:SS'),
        TO_CHAR(SYSTIMESTAMP, 'YYYY-MM-DD AM HH:MI:SS.FF3')
FROM DUAL;