--SELECT 'DROP TABLE "' || TABLE_NAME || '" CASCADE CONSTRAINTS;' FROM user_tables;

DROP TABLE "DEPARTMENT_TBL" CASCADE CONSTRAINTS;
DROP TABLE "EMPLOYEE_TBL" CASCADE CONSTRAINTS;
DROP TABLE "PROJECT_TBL" CASCADE CONSTRAINTS;
DROP TABLE "PROCEEDING_TBL" CASCADE CONSTRAINTS;